### ISSUE TITLE
Warning showing when app start and blank screen appears

### ISSUE THREAD

**Issue by jorgevalbuena56** [khriztianmoreno/ecommerce-react-native#1]
Hi

I am getting the following error running the app:

![screenshot_20180130-221638](https://user-images.githubusercontent.com/7516423/35566015-92dba32a-060b-11e8-8cc1-9d667c4d2eed.png)

My env is:

npm -version
4.6.1
yarn -version
1.3.2
node --version
v8.9.4

**Comment by khriztianmoreno** [comment]
@jorgevalbuena56  This project is for academic purposes, all your data is stored in variables within the code, a **warning** like this *(it is not an error)* could only happen if you already modified the base code or the versions that you use of some of the dependencies have been updated , block these dependencies to the version described in the `package.json` to avoid future warnings.
